### ISSUE TITLE
Error getting IBMQ device status

### ISSUE THREAD

**Issue by cbjuan** [Qiskit/qiskit-vscode#2]
### Informations

- **VSCode version**: 1.25.1
- **Qiskit (Python SDK) version**: 0.5.6
- **Qiskit VSCode Extension version**: 0.2.2
- **Operating system**: Windows 7

### What is the current behavior?
When getting the status of the IBM Q Experience's devices in Windows 7, we get an error with the following stacktrace:

```
Traceback (most recent call last):
  File "c:\Users\AlbertFrisch\.vscode\extensions\ibm-research.ibm-q-studio-0.2.2\resources\qiskitScripts\listRemoteBackends.py", line 83, in <module>
    main()
  File "c:\Users\AlbertFrisch\.vscode\extensions\ibm-research.ibm-q-studio-0.2.2\resources\qiskitScripts\listRemoteBackends.py", line 54, in main
    statusDevices = list(p.map(createDeviceStatus, backs))
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
LookupError: backend "ibmq_16_rueschlikon" not found.
```

### Steps to reproduce the problem
Click on the button `IBMQ devices status` and the error appears

### What is the expected behavior?
To don't get the error and get the visualization of the devices' status

### Suggested solutions
Replace the current `pool.map` method by other that works smoother in Windows

**Comment by cbjuan** [comment]
Solved in #6
